# Generated by Django 3.2.6 on 2021-08-08 22:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250, unique=True)),
                ('password', models.CharField(blank=True, max_length=250, null=True)),
                ('member_type', models.CharField(choices=[('A', 'Admin'), ('U', 'User')], default='U', max_length=2)),
            ],
            options={
                'verbose_name_plural': 'members',
                'db_table': 'member',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('performance', models.TextField()),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.member')),
            ],
            options={
                'db_table': 'performance_review',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='AssignedReviewer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('performance_review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.performancereview')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_assigned', to='api.member')),
            ],
            options={
                'db_table': 'assigned_reviewer',
                'ordering': ('-updated_at',),
                'unique_together': {('performance_review', 'reviewer')},
            },
        ),
    ]
